language: node_js
node_js:
  - v8
script:
  - yarn lint
  - yarn test --coverage
  - yarn type-check
  - yarn build
cache: 
  - yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - bash <(curl -s https://codecov.io/bash)
