name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn test --coverage
      - run: yarn type-check
      - run: yarn build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
